server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Redirige cualquier petición al index.html para que React Router maneje las rutas
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Optimización de compilación gzip para mejor rendimiento
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
}